name: Ci pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies for backend
        working-directory: todo-backend
        run: npm install

      - name: Run tests for backend
        working-directory: todo-backend
        run: npx test

      - name: Install dependencies for frontend
        working-directory: todo-backend
        run: npm install

      - name: Run tests for frontend
        working-directory: todo-backend
        run: npm test
